#26070: 25994 - make payment options consistent
BudsiesApp/vsf-payment-braintree pull request #2
Opened 2022-03-15 10:22 UTC by soarer1004

2022-03-25 14:55 UTC, gorbunovav requested changes

2022-03-25 14:55 UTC, gorbunovav commented on components/payment-apple-pay.vue
> +     !(this.window as any).ApplePaySession.canMakePayments()
Там судя по примеру нужно проверять наличие `window.ApplePaySession` для определения поддержки Apple Pay, но дальше обращаться напрямую к классу, т.к. методы статические (т.е. не через window):

https://developer.paypal.com/braintree/docs/guides/apple-pay/client-side#check-browser-and-device-capabilities

2022-03-25 14:55 UTC, gorbunovav commented on mixins/PaymentMethod.ts
> +  },
а для чего нам отслеживать выбранный метод оплаты внутри компонентов? у нас же вроде как каждый компонент отвечает только за один метод

2022-03-25 14:55 UTC, gorbunovav commented on components/payment-apple-pay.vue
> +        });
А почему мы эти данные именно в store сохраняем? 
Получается там же может быть только одно значение и нет никакой информации о заказе, к которому эти данные относятся.
Т.е. видимо отсюда возникаем, например, проблема c "Cannot use a payment_method_nonce more than once. Please try again or attempt refreshing the page." при повторной отправке заказов.

2022-03-28 03:42 UTC, soarer1004 commented on mixins/PaymentMethod.ts
> +  },
@gorbunovav Это сделано для определения отображать или нет контент методов оплаты(Поля ввода для карты и кнопку PayPal).

2022-03-28 04:16 UTC, soarer1004 commented on components/payment-apple-pay.vue
> +        });
@gorbunovav Чтобы не передавать эти данные через несколько событий(Через события получается более запутано). Проблема с "Cannot use a payment_method_nonce more than once" будет возникать в любом случае до фикса https://redmine.optimuspro.ru/issues/26158 . Т.к. эти данные сохранятся в заказе, который будет в очереди и при повторном отправлении запроса на создание заказа они будут использованы. А при повторном нажатии пользователем на кнопку "Place Order", эти данные в Store будут перезаписаны на актуальные, и такой проблемы не возникает. Как вариант, можно после вызова события `checkout-do-placeOrder` очищать эти данные в store.

2022-03-28 10:25 UTC, gorbunovav commented on mixins/PaymentMethod.ts
> +  },
@soarer1004 мне кажется через props логичнее - компонент же не отвечает за общую логику работы формы

2022-03-28 10:33 UTC, soarer1004 commented on mixins/PaymentMethod.ts
> +  },
@gorbunovav `getPaymentMethodCode` тоже тогда удалю из миксина и заменю на константу в компоненте

2022-03-28 10:45 UTC, gorbunovav commented on components/payment-apple-pay.vue
> +        });
@soarer1004 да, там видимо сложновато переделать будет.
Тогда да, думаю стоит добавить очистку данных, когда они уже не актуальны.

2022-03-28 10:46 UTC, gorbunovav commented on mixins/PaymentMethod.ts
> +  },
@soarer1004 ага

2022-03-28 10:47 UTC, soarer1004 commented on components/payment-apple-pay.vue
> +        });
@gorbunovav Очистку данных добавил

2022-03-28 10:47 UTC, soarer1004 commented on mixins/PaymentMethod.ts
> +  },
@gorbunovav исправил. Там еще коммит запушил в репозиторий темы

2022-03-28 11:03 UTC, gorbunovav commented on components/payment-apple-pay.vue
> +     !(this.window as any).ApplePaySession.canMakePayments()
>ApplePaySession = (this.window as any).ApplePaySession;

@soarer1004 так а что изменилось? ты просто использовал промежуточную переменную, это не обращение к статическому методу класса.

Тебе нужно импортировать класс `ApplePaySession` и вызывать его метод

2022-03-28 11:10 UTC, soarer1004 commented on components/payment-apple-pay.vue
> +     !(this.window as any).ApplePaySession.canMakePayments()
@gorbunovav Видимо я не совсем правильно понял. ApplePaySession это же просто глобальная переменная в Safari?

2022-03-28 11:14 UTC, gorbunovav commented on components/payment-apple-pay.vue
> +     !(this.window as any).ApplePaySession.canMakePayments()
@soarer1004 хм, похоже да.
Но в SDK для braintree есть type definition для этого класса и его можно импортировать.
При этом если обращаться через window, то он будет ругаться на неправильный вызов статического метода 🤔

2022-03-28 11:23 UTC, soarer1004 commented on components/payment-apple-pay.vue
> +     !(this.window as any).ApplePaySession.canMakePayments()
@gorbunovav Хм, при использовании этого класса, в консоль ошибка падает

2022-03-28 11:27 UTC, soarer1004 commented on components/payment-apple-pay.vue
> +     !(this.window as any).ApplePaySession.canMakePayments()
@gorbunovav Класс то, получается, абстрактный. Его, получается, только в качестве типа можно использовать

2022-03-28 11:30 UTC, soarer1004 commented on components/payment-apple-pay.vue
> +     !(this.window as any).ApplePaySession.canMakePayments()
@gorbunovav А, ну да, если его  в качестве типа использовать - TS ругается. Если использовать как класс со статическими методами - падает в рантайме ошибка

2022-03-28 12:26 UTC, gorbunovav commented on components/payment-apple-pay.vue
> +     !(this.window as any).ApplePaySession.canMakePayments()
@soarer1004 возможно что то не то с type definition 🤔
Ок, давай так оставим пока

2022-03-28 12:27 UTC, gorbunovav approved these changes

2022-03-28 12:28 UTC, merged